### ISSUE TITLE
Could not find com.huangyz0918:androidwm-light:0.1.2.

### ISSUE THREAD

**Issue by merbin2012** [kuamanet/cordova-pdf-reader#6]
Thanks for making this plugin, while trying to build the following error is showing

`> Task :app:checkDebugAarMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.huangyz0918:androidwm:0.2.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huangyz0918/androidwm/0.2.3/androidwm-0.2.3.pom
       - https://repo.maven.apache.org/maven2/com/huangyz0918/androidwm/0.2.3/androidwm-0.2.3.pom
       - https://jcenter.bintray.com/com/huangyz0918/androidwm/0.2.3/androidwm-0.2.3.pom
       - https://maven.ghostscript.com/com/huangyz0918/androidwm/0.2.3/androidwm-0.2.3.pom
     Required by:
         project :app`

**Comment by kuamanet** [comment]
Hello, odd error. The package is reachable, I just tried to create an empty cordova project and added my plugin, it builds just fine... what cordova / gradle version are you using?
